version: "3.8"
services:
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - ${PG_PORT:-5432}:5432
    volumes:
      - .docker-data/pg-data:/var/lib/postgresql/data:consistent
      - .docker-data/pg-backup:/backup:consistent
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20

  hasura:
    build:
      context: ./services/hasura
    ports:
      - ${HASURA_PORT:-8080}:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-qwerty}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"dd5dd7i2vddf786vs7v3fgb87987vdsc7sd98"}'
      EVT_PRODUCTS_CACHE_UPDATE: http://products:8080/on-products-cache-updates
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 5s
      retries: 20

  migrations:
    build:
      context: ./services/migrations
    depends_on:
      hasura:
        condition: service_healthy
    volumes:
      - ./services/migrations/metadata:/metadata:cached
      - ./services/migrations/migrations:/migrations:cached
      - ./services/migrations/seeds:/seeds:cached
    environment:
      HASURA_ENDPOINT: http://hasura:8080
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-qwerty}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    stdin_open: true
    tty: true

  sot_products:
    image: node:14-alpine
    volumes:
      - .docker-data/sot_products/node_modules:/usr/src/app/node_modules:cached
      - ./services/sot_products/package.json:/usr/src/app/package.json:delegated
      - ./services/sot_products/package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./services/sot_products/src:/usr/src/app/src:delegated
    environment:
      NODE_ENV: development
      HASURA_URL: http://hasura:8080/v1/graphql
      HASURA_KEY: eyJhbGciOiJIUzI1NiJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsic290X3Byb2R1Y3RzIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InNvdF9wcm9kdWN0cyJ9fQ.iI8LdiYrS3k_N8iKTYYmj8kewSVBUBwR9JAIGbgPzqs
      PGSTRING: postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - ${PRODUCTS_PORT:-4000}:8080
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "start:docker"]
    depends_on:
      postgres:
        condition: service_healthy

  products_cache:
    image: node:14-alpine
    volumes:
      - .docker-data/products_cache/node_modules:/usr/src/app/node_modules:cached
      - ./services/products_cache/package.json:/usr/src/app/package.json:delegated
      - ./services/products_cache/package-lock.json:/usr/src/app/package-lock.json:delegated
      - ./services/products_cache/src:/usr/src/app/src:delegated
    environment:
      NODE_ENV: development
      PGSTRING: postgresql://postgres:postgres@postgres:5432/postgres
      CURSOR_ID: products_cache
    ports:
      - ${PRODUCTS_PORT:-4000}:8080
    working_dir: /usr/src/app
    entrypoint: ["npm", "run", "start:docker"]
    depends_on:
      postgres:
        condition: service_healthy
